version: '3'

# Networks
networks:
  demo-network:
    driver: bridge

# Services
services:
  # web service
  web:
#    image: library/nginx:1.19
    build: .docker/nginx/
    container_name: web
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    tty: true
    volumes:
      - ../:/var/www/demo:rw
      - ./.docker/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./.docker/nginx/conf.d/demo.conf:/etc/nginx/conf.d/demo.conf:rw
    depends_on:
      - php-fpm
    networks:
      - demo-network
  # PHP-FPM service
  php-fpm:
    build: .docker/php/
    container_name: php-fpm
    working_dir: /var/www/demo/app
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/demo/app
    depends_on:
      - db
    networks:
      - demo-network
  # db service
  db:
    image: library/postgres:13
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data:rw
      - ./.docker/postgres/dump:/dump:ro
    networks:
      - demo-network